---
version: "3.9"

services:
  dockerapp: 
    container_name: appcont
    build: ./Docker-app/
    ports:
      - "8081:8080"
    volumes:
      - appvol: /app/vol/

  dockerdb:
    container_name: dbcont
    build: ./Docker-db/
    ports:
      - "3306:3306"
    volumes:
      - dbvol: /db/vol/

volumes:
  appvol: 
    driver: local
  dbvol:
    driver: local
    
