---
version: "3.9"

services:
  dockerapp: 
    image: geyachiramdasu08/appimg:app
    ports:
      - "9999:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb

  devopsdb:
    image: geyachiramdasu08/dbimg:db
    ports:
      - "3306:3306"
    deploy:
      replicas: 3

    
